org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
minecraft_version=1.21.4
loader_version=0.16.9
fabric_api_version=0.119.4+1.21.4
mcef_version=2.1.6-1.21.4
jcef_commit=2eb4ca2648bda91d1dfed81e9a37ba92e757aff9
cef_commit=89cd5813e47d84c68e56ced336c2c01b7dc77b8d
chromium_version=151.0.7922.34
chromium_runtime_version=151.0.7922.34-wlc.2
mod_version=0.1.96-dev
